
// Summary of comments:

// - Each line is annotated with a short comment describing its purpose. Do not manually remove required members; update the .resx and rebuild instead.

namespace CyberAwarenessBot.Properties // Namespace grouping project resources
{

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")] // Generator metadata
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()] // Skip stepping into this code during debugging
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()] // Mark as compiler-generated
    internal class Resources // Strongly-typed resource wrapper class
    {

        // Backing field for the lazily-initialized ResourceManager instance
        private static global::System.Resources.ResourceManager resourceMan;

        // Backing field for an optional culture override used when looking up resources
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] // Suppress performance warning for the default ctor
        internal Resources() // Private/internal default constructor (unused; class is static-like)
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] // Hide from typical IntelliSense
        internal static global::System.Resources.ResourceManager ResourceManager // Public accessor for the ResourceManager
        {
            get
            {
                if ((resourceMan == null)) // If not yet created, construct and cache it
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberAwarenessBot.Properties.Resources", typeof(Resources).Assembly); // Create manager for this assembly
                    resourceMan = temp; // Cache instance for subsequent lookups
                }
                return resourceMan; // Return cached ResourceManager
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] // Advanced editor browsing
        internal static global::System.Globalization.CultureInfo Culture // Optional culture override for resource lookups
        {
            get
            {
                return resourceCulture; // Return currently set culture (may be null)
            }
            set
            {
                resourceCulture = value; // Set culture override for subsequent lookups
            }
        }
    }
}
