
// Summary of comments:

// - Each code line is preceded by a short comment explaining its purpose for maintainability and readability.

// Declare the namespace that groups project settings types
namespace CyberAwarenessBot.Properties
{
    // Compiler-generated attribute indicates this class was generated by a tool
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    // Attribute noting the source generator and its version
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    // Internal sealed partial class representing the application's settings container
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        // Static singleton instance used to access the settings at runtime
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        // Public accessor for the shared Settings instance
        public static Settings Default
        {
            // Getter returns the synchronized singleton instance
            get
            {
                return defaultInstance;
            }
        }
    }
}
